db:
  username: postgres
  password: 123
  driver: PostgresDriver
  url: postgres:5432
  pool:
    size: 10
    timeout: 20


spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto : validate
    open-in-view: false

app:
  image:
    bucket: /Users/oksanavorobeva/Desktop/Java/SpringБорисов/myProject/images

app.service.logging:
  enabled: true

logging:
  level:
    root: info
  file:
   name: by.javaguru
   path: /
