CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    firstname  VARCHAR(255),
    lastname   VARCHAR(255),
    password   VARCHAR(255)                            NOT NULL,
    birth_date date,
    image      VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);
ALTER TABLE users
    ADD image VARCHAR(255);

ALTER TABLE users
    ADD password VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN password SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

DROP TABLE chat CASCADE;

DROP TABLE company CASCADE;

DROP TABLE payment CASCADE;

DROP TABLE profile CASCADE;

DROP TABLE user_chat CASCADE;

ALTER TABLE users
    DROP COLUMN company_id;

DROP SEQUENCE chat_id_seq CASCADE;

DROP SEQUENCE company_id_seq CASCADE;

DROP SEQUENCE payment_id_seq CASCADE;

DROP SEQUENCE profile_id_seq CASCADE;

DROP SEQUENCE user_chat_id_seq CASCADE;

DROP SEQUENCE users_id_seq CASCADE;

DROP SEQUENCE users_seq CASCADE;

ALTER TABLE users
    ALTER COLUMN username SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT pk_users PRIMARY KEY (id);